import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Andrea
 */
public class PaginaDomande extends javax.swing.JFrame {

    /**
     * Creates new form PaginaDomande
     */
    private ConnessioneSocket conn;
    private int numeroDomanda = 0;
    private int totaleDomande = 10; 
    public PaginaDomande(ConnessioneSocket conn) {//costruttore
        this.conn = conn;
        initComponents();
        startDomande(); //inizia le domande
    }

    private void startDomande() {
        new Thread(() -> { //apro un thread per le domande
            try {
                String msg;
                while ((msg = conn.leggiMessaggio()) != null) {

                    if (msg.startsWith("DOMANDA|")) { //se il messaggio che ottiene dal socket contiene la domanda
                        numeroDomanda++; //incrementa il numero delle domande per mostrare a quale domanda sul tot si è
                        String testoDomanda = msg.substring("DOMANDA|".length());//il formato che prende dal socket è DOMANDA|testoDomanda quindi suddivide per ottennere solo il testo

                        SwingUtilities.invokeLater(() -> { //solo una volta che ha ottenuto il testo via socket,apre la swing e mostra la textArea ecc
                            jTextArea1.setText(testoDomanda);
                            jLabelNumeroDomande.setText("Domanda " + numeroDomanda + " di " + totaleDomande);
                        });
                    }
                     //se ha finito le domande , quindi riceve un messaggio con il punteggio
                    if (msg.startsWith("PUNTEGGIO|")) {
                        String punteggio = msg.substring("PUNTEGGIO|".length()); //prendo solo il punteggio dalla riga che ricevo dal socket
                        JOptionPane.showMessageDialog(this, "Hai totalizzato: " + punteggio + " punti!");
                        PaginaClassifica classifica = new PaginaClassifica(conn,Integer.parseInt(punteggio));//passo alla pagina classifica il punteggio e il riferimento alla connessione
                        classifica.setVisible(true); //mostro la pagina classifica
                        this.dispose();//chiudo domande
}
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null,
                        "Connessione persa con il server.",
                        "Errore",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroDomande = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRisposte = new javax.swing.JTextField();
        jButtonInvia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNumeroDomande.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelNumeroDomande.setText("Domanda i di n");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Inserisci la tua risposta");

        jButtonInvia.setText("Invia");
        jButtonInvia.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInviaActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumeroDomande)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRisposte, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInvia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelNumeroDomande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRisposte, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonInvia, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInviaActionPerformed
        // TODO add your handling code here:
        String risposta = jTextFieldRisposte.getText().trim();
            if (!risposta.isEmpty()) {
                conn.inviaRisposta(risposta);
                jTextFieldRisposte.setText("");
            }
    }//GEN-LAST:event_jButtonInviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaDomande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaDomande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaDomande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaDomande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInvia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNumeroDomande;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldRisposte;
    // End of variables declaration//GEN-END:variables
}
